  
  - name: BACKUP IOS CONFIGS
    hosts: iosxe
    connection: local
    gather_facts: no
    tags: ios

    tasks:

      - name: BACKUP IOS CONFIGS
        ios_command:
          commands: "{{ config[os] }}"
        register: config_data

      - name: SAVE CONFIG TO FILE
        template: 
          src: basic-copy.j2
          dest: ./backups/{{ inventory_hostname }}.cfg

  - name: BACKUP NXOS CONFIGS
    hosts: nxos
    connection: local
    gather_facts: no
    tags: nxos

    tasks:

      - name: BACKUP NXOS CONFIGS
        nxos_command:
          commands: "{{ config[os] }}"
        register: config_data

      - name: SAVE CONFIG TO FILE
        template: 
          src: basic-copy.j2
          dest: ./backups/{{ inventory_hostname }}.cfg

  - name: BACKUP VMX CONFIGS
    hosts: vmx
    connection: local
    gather_facts: no
    tags: vmx

    tasks:

      - name: BACKUP VMX CONFIGS
        junos_command:
          commands: "{{ config[os] }}"
        register: config_data

      - name: SAVE CONFIG TO FILE
        template: 
          src: basic-copy.j2
          dest: ./backups/{{ inventory_hostname }}.cfg

  - name: BACKUP EOS CONFIGS 
    hosts: eos
    connection: local
    gather_facts: no
    tags: eos

    tasks:
      - name: BACKUP EOS CONFIGS
        eos_command:
          commands: "{{ config[os] }}"
        register: config_data

      - name: SAVE CONFIG TO FILE
        template: 
          src: basic-copy.j2
          dest: ./backups/{{ inventory_hostname }}.cfg
