---

  - name: PLAY 1 - BUILD CONFIGS
    hosts: iosxe,nxos
    gather_facts: no

    tasks:

      - name: BUILD CONFIGS
        template: 
          src: interfaces.j2
          dest: ./configs/{{ inventory_hostname }}.cfg

  - name: PLAY 2 - DEPLOY IOS
    hosts: iosxe
    gather_facts: no

    tasks:

      - name: DEPLOY CONFIGURATION
        ios_config:
          src: ./configs/{{ inventory_hostname }}.cfg

  - name: PLAY 3 - DEPLOY NXOS
    hosts: nxos
    gather_facts: no

    tasks:

      - name: DEPLOY CONFIGURATION
        nxos_config:
          src: ./configs/{{ inventory_hostname }}.cfg